version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: smart-campus-db
    environment:
      POSTGRES_DB: smart_campus_prod
      POSTGRES_USER: smart_campus_user
      POSTGRES_PASSWORD: your_secure_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - smart-campus-network

  # Redis for Session Storage
  redis:
    image: redis:7-alpine
    container_name: smart-campus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - smart-campus-network

  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-campus-app
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://smart_campus_user:your_secure_db_password@postgres:5432/smart_campus_prod
      REDIS_URL: redis://redis:6379
      FRONTEND_URL: https://your-domain.com
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/backend/logs
    networks:
      - smart-campus-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: smart-campus-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - smart-campus-network

volumes:
  postgres_data:
  redis_data:

networks:
  smart-campus-network:
    driver: bridge