services:
  # PostgreSQL Database
  - type: pserv
    name: smart-campus-db
    env: node
    plan: starter
    buildCommand: echo "Database service"
    startCommand: echo "Database running"
    envVars:
      - key: POSTGRES_DB
        value: smart_campus_prod
      - key: POSTGRES_USER
        value: smart_campus_user
      - key: POSTGRES_PASSWORD
        generateValue: true

  # Backend API Service
  - type: web
    name: smart-campus-api
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm run migrate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: smart-campus-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://smart-campus-portal.onrender.com
      - key: PORT
        value: 5000

  # Frontend Web Service
  - type: web
    name: smart-campus-portal
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://smart-campus-api.onrender.com

databases:
  - name: smart-campus-db
    databaseName: smart_campus_prod
    user: smart_campus_user
    plan: starter